import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function About() {
	
  return (

    <div className={styles.container}>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main className={styles.main}>

			<div className={styles.title}>About</div>
			<p className={styles.description}>
				Get started by editing{' '}
				<code className={styles.code}>pages/index.js</code>
			</p>
	

			<Link href="/">
				<a className={styles.link}>Back to Top</a>
			</Link>
		</main>
			
		</div>
	)
}
